export const ProfileFormData = [
    {
        id: 'firstName',
        name: 'firstName',
        title: 'First Name',
        type: 'text',
        placeholder: 'Please enter your first name',
    },
    {
        id: 'lastName',
        name: 'lastName',
        title: 'Last Name',
        type: 'text',
        placeholder: 'Please enter your last name',
    },
    {
        id: 'idNumber',
        name: 'idNumber',
        title: 'ID Number',
        type: 'text',
        placeholder: 'Please enter your ID number',
    },
    {
        id: 'phoneNumber',
        name: 'phoneNumber',
        title: 'Phone Number',
        type: 'text',
        placeholder: 'Please enter your phone number',
    },
    {
        id: 'address',
        name: 'address',
        title: 'Address',
        type: 'text',
        placeholder: 'Please enter your address',
    },
    {
        id: 'email',
        name: 'email',
        title: 'Email',
        type: 'email',
        placeholder: 'Please enter your email',
    },
    // {
    //     id: 'password',
    //     name: 'password',
    //     title: 'Password',
    //     type: 'password',
    //     placeholder: 'Please enter your password',
    // },
];
